import "./globals.css";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";

import { Cairo } from "next/font/google";

const cairo = Cairo({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Ramita Media",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body className={cairo.className}>
        <Header />
        <div className="container">
        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
